# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelledDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField()),
                ('document_id', models.PositiveIntegerField()),
                ('value', models.TextField()),
                ('document_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='labelleddocument',
            unique_together=set([('model_name', 'document_content_type', 'document_id')]),
        ),
    ]
