# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_learnit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelleddocument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labelleddocument',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
